# Generated by Django 4.2.7 on 2025-07-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short, one sentence description of the incident', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what is known about the incident')),
                ('level', models.CharField(blank=True, choices=[('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5')], max_length=3)),
                ('scope', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('safety_compliance', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not known yet', 'Not known yet')], max_length=15)),
                ('security_privacy', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not known yet', 'Not known yet')], max_length=15)),
                ('data_quality', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not known yet', 'Not known yet')], max_length=15)),
                ('psd2_impact', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not known yet', 'Not known yet')], max_length=15)),
                ('started_at', models.DateTimeField(help_text='When the incident started')),
                ('detected_at', models.DateTimeField(help_text='When the incident was detected')),
                ('time_format', models.CharField(choices=[('Local Time', 'Local Time'), ('UTC', 'UTC')], default='Local Time', max_length=15)),
                ('detection_source', models.CharField(choices=[('Manual', 'Manual'), ('Automated', 'Automated')], default='Manual', max_length=15)),
                ('incident_type', models.CharField(choices=[('Planned', 'Planned'), ('Outage', 'Outage'), ('External', 'External')], default='Planned', max_length=10)),
                ('impacted_locations', models.JSONField(default=list, help_text='List of impacted geographical locations')),
                ('impacted_parties', models.JSONField(default=list, help_text='List of impacted parties/user groups')),
                ('incident_commander', models.EmailField(help_text='Email of the incident commander', max_length=254)),
                ('reporting_org', models.CharField(help_text='Organization reporting the incident', max_length=100)),
                ('estimated_time_to_mitigation', models.CharField(blank=True, default='unknown', max_length=20)),
                ('first_detected_in', models.CharField(blank=True, help_text='Where the incident was first detected', max_length=50)),
                ('impacted_assets', models.CharField(blank=True, help_text='Assets experiencing side effects', max_length=50)),
                ('impacted_areas', models.CharField(blank=True, help_text='Technical areas impacted', max_length=50)),
                ('additional_subscribers', models.TextField(blank=True, help_text='Additional email subscribers')),
                ('related_documents', models.JSONField(default=list, help_text='List of related document links')),
                ('safety_compliance_document_url', models.URLField(blank=True, help_text='URL for safety compliance documentation')),
                ('l5_confirmation', models.BooleanField(default=False, help_text='L5 incident confirmation')),
                ('mitigation_policy_acknowledgment', models.BooleanField(default=False, help_text='Mitigation policy acknowledgment')),
                ('send_email_notifications', models.BooleanField(default=True, help_text='Send email notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('url', models.URLField(help_text='Document URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident Document',
                'verbose_name_plural': 'Incident Documents',
                'ordering': ['created_at'],
            },
        ),
    ]
