# Generated by Django 4.2.7 on 2025-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_convert_string_to_json_arrays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='impacted_areas',
            field=models.JSONField(default=list, help_text='List of technical areas impacted'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='impacted_assets',
            field=models.JSONField(default=list, help_text='List of assets experiencing side effects'),
        ),
    ]
