# Generated by Django 4.2.7 on 2025-07-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_incident_impacted_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='related_documents',
        ),
    ]
